// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB694ZOA4AHyyPCTKAPr29scsrInI07_H4',
    appId: '1:801401171814:web:f315ba3015b65e293ba2a7',
    messagingSenderId: '801401171814',
    projectId: 'my-authentication-build-app',
    authDomain: 'my-authentication-build-app.firebaseapp.com',
    storageBucket: 'my-authentication-build-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFOoTMrRSIPX1cJAau5eHfST4CnAt6Da0',
    appId: '1:801401171814:android:732b48b5e52a67413ba2a7',
    messagingSenderId: '801401171814',
    projectId: 'my-authentication-build-app',
    storageBucket: 'my-authentication-build-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jhUPmxGWjcojAp0zSanGoBA9DVGYrcs',
    appId: '1:801401171814:ios:e149182553f6bbdf3ba2a7',
    messagingSenderId: '801401171814',
    projectId: 'my-authentication-build-app',
    storageBucket: 'my-authentication-build-app.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jhUPmxGWjcojAp0zSanGoBA9DVGYrcs',
    appId: '1:801401171814:ios:e149182553f6bbdf3ba2a7',
    messagingSenderId: '801401171814',
    projectId: 'my-authentication-build-app',
    storageBucket: 'my-authentication-build-app.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB694ZOA4AHyyPCTKAPr29scsrInI07_H4',
    appId: '1:801401171814:web:59fbdc68c09ef4603ba2a7',
    messagingSenderId: '801401171814',
    projectId: 'my-authentication-build-app',
    authDomain: 'my-authentication-build-app.firebaseapp.com',
    storageBucket: 'my-authentication-build-app.firebasestorage.app',
  );
}
